/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shapeworld;

import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Sanuth Nethika
 */
public class ShapeMenu extends javax.swing.JFrame {
    //Square ICON Get
    ImageIcon Square_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconSquare.png"));  
    ImageIcon Square_hover_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconSquare-hover.png"));
    //Circle ICON Get
    ImageIcon Circle_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconCircle.png"));  
    ImageIcon Circle_hover_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconCircle-hover.png"));
    //Hexagon ICON Get
    ImageIcon Hexagon_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconHexagon.png"));  
    ImageIcon Hexagon_hover_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconHexagon-hoverr.png"));
    //Rectangle ICON get
    ImageIcon Rectangle_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconRectangle.png"));  
    ImageIcon Rectangle_hover_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconRectangle-hover.png"));
    //Triangle ICON Get
    ImageIcon Triangle_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconTriangle.png"));  
    ImageIcon Triangle_hover_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconTriangle-hover.png"));
    //Home ICOn Get
    ImageIcon Home_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconHome.png"));  
    ImageIcon Home_hover_img = new javax.swing.ImageIcon(getClass().getResource("/Image/IconHome-hover.png"));
    
    
    public ShapeMenu() {
        initComponents();
         this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Image/Logo.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMainTitle = new javax.swing.JLabel();
        lblTriangle = new javax.swing.JLabel();
        lblcircle = new javax.swing.JLabel();
        lblSquare = new javax.swing.JLabel();
        lblRectangle = new javax.swing.JLabel();
        lblHexagon = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(1111, 575));
        setResizable(false);
        setSize(new java.awt.Dimension(1111, 575));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMainTitle.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblMainTitle.setForeground(new java.awt.Color(0, 153, 0));
        lblMainTitle.setText("You can Select and see the Shapes!");
        getContentPane().add(lblMainTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        lblTriangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconTriangle.png"))); // NOI18N
        lblTriangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTriangleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblTriangleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTriangleMouseExited(evt);
            }
        });
        getContentPane().add(lblTriangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lblcircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconCircle.png"))); // NOI18N
        lblcircle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcircleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcircleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcircleMouseExited(evt);
            }
        });
        getContentPane().add(lblcircle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        lblSquare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconSquare.png"))); // NOI18N
        lblSquare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSquareMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSquareMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSquareMouseExited(evt);
            }
        });
        getContentPane().add(lblSquare, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 160, -1, -1));

        lblRectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconRectangle.png"))); // NOI18N
        lblRectangle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRectangleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRectangleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblRectangleMouseExited(evt);
            }
        });
        getContentPane().add(lblRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        lblHexagon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconHexagon.png"))); // NOI18N
        lblHexagon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHexagonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHexagonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHexagonMouseExited(evt);
            }
        });
        getContentPane().add(lblHexagon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/IconHome.png"))); // NOI18N
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHomeMouseExited(evt);
            }
        });
        getContentPane().add(lblHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PanelBackground.png"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblSquareMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSquareMouseEntered
        lblSquare.setIcon(Square_hover_img);
    }//GEN-LAST:event_lblSquareMouseEntered

    private void lblSquareMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSquareMouseExited
        lblSquare.setIcon(Square_img);
    }//GEN-LAST:event_lblSquareMouseExited

    private void lblcircleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcircleMouseEntered
        lblcircle.setIcon(Circle_hover_img);
    }//GEN-LAST:event_lblcircleMouseEntered

    private void lblcircleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcircleMouseExited
         lblcircle.setIcon(Circle_img);
    }//GEN-LAST:event_lblcircleMouseExited

    private void lblHexagonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHexagonMouseEntered
        lblHexagon.setIcon(Hexagon_hover_img);
    }//GEN-LAST:event_lblHexagonMouseEntered

    private void lblHexagonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHexagonMouseExited
        lblHexagon.setIcon(Hexagon_img);
    }//GEN-LAST:event_lblHexagonMouseExited

    private void lblRectangleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRectangleMouseEntered
        lblRectangle.setIcon(Rectangle_hover_img);
    }//GEN-LAST:event_lblRectangleMouseEntered

    private void lblRectangleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRectangleMouseExited
         lblRectangle.setIcon(Rectangle_img);
    }//GEN-LAST:event_lblRectangleMouseExited

    private void lblTriangleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTriangleMouseEntered
        lblTriangle.setIcon(Triangle_hover_img);
    }//GEN-LAST:event_lblTriangleMouseEntered

    private void lblTriangleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTriangleMouseExited
        lblTriangle.setIcon(Triangle_img);
    }//GEN-LAST:event_lblTriangleMouseExited

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
         Home H = new Home();
        H.show();
        this.hide();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseEntered
        lblHome.setIcon(Home_hover_img);
    }//GEN-LAST:event_lblHomeMouseEntered

    private void lblHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseExited
        lblHome.setIcon(Home_img);
    }//GEN-LAST:event_lblHomeMouseExited

    private void lblRectangleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRectangleMouseClicked
       Rectangle R = new Rectangle();
       R.show();
       this.hide();
    }//GEN-LAST:event_lblRectangleMouseClicked

    private void lblTriangleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTriangleMouseClicked
        Triangle T = new Triangle();
        T.show();
        this.hide();
    }//GEN-LAST:event_lblTriangleMouseClicked

    private void lblSquareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSquareMouseClicked
        Square S = new Square();
        S.show();
        this.hide();
    }//GEN-LAST:event_lblSquareMouseClicked

    private void lblcircleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcircleMouseClicked
        Circle C = new Circle();
        C.show();
        this.hide();
    }//GEN-LAST:event_lblcircleMouseClicked

    private void lblHexagonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHexagonMouseClicked
        Hexagon H = new Hexagon();
        H.show();
        this.hide();
    }//GEN-LAST:event_lblHexagonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShapeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShapeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShapeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShapeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShapeMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel lblHexagon;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblMainTitle;
    private javax.swing.JLabel lblRectangle;
    private javax.swing.JLabel lblSquare;
    private javax.swing.JLabel lblTriangle;
    private javax.swing.JLabel lblcircle;
    // End of variables declaration//GEN-END:variables
}
